name: Trigger auto deployment for react-docker-azure-deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/react-docker-azure-deployment-AutoDeployTrigger-0b64db9c-75fe-4ef6-a7f7-83a87ec96fc5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.REACTDOCKERAZUREDEPLOYMENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REACTDOCKERAZUREDEPLOYMENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REACTDOCKERAZUREDEPLOYMENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: reactdockerazuredeployment.azurecr.io
          registryUsername: ${{ secrets.REACTDOCKERAZUREDEPLOYMENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REACTDOCKERAZUREDEPLOYMENT_REGISTRY_PASSWORD }}
          containerAppName: react-docker-azure-deployment
          resourceGroup: react-docker-rg
          imageToBuild: reactdockerazuredeployment.azurecr.io/react-docker-azure-deployment:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


